# Generated by Django 5.1.4 on 2025-01-13 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentalApp', '0005_alter_service_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_number', models.CharField(help_text='Formato: 573202274345', max_length=20)),
                ('phone_number', models.CharField(help_text='Formato: +573202274345', max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('facebook_url', models.URLField(verbose_name='URL de Facebook')),
                ('instagram_url', models.URLField(verbose_name='URL de Instagram')),
                ('is_whatsapp_active', models.BooleanField(default=True)),
                ('is_phone_active', models.BooleanField(default=True)),
                ('is_email_active', models.BooleanField(default=True)),
                ('is_facebook_active', models.BooleanField(default=True)),
                ('is_instagram_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Configuración de Redes Sociales',
                'verbose_name_plural': 'Configuración de Redes Sociales',
            },
        ),
    ]
