# Generated by Django 5.1.4 on 2025-01-14 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentalApp', '0008_delete_banner_appointment_status_alter_service_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='google_calendar_event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
